// <auto-generated>
//      Only to fool StyleCop. This file is NOT auto-generated.
// </auto-generated>
namespace NHibernate.FlowQuery
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery" /> namespace contains fundamental classes for using the project with
    ///     <see cref="NHibernate" />.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.AutoMapping
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.AutoMapping" /> namespace contains basic classes and interfaces used by
    ///     <see cref="NHibernate.FlowQuery" /> to map objects of one <see cref="System.Type" /> to another.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Core
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Core" /> namespace contains all interface declarations and classes
    ///     defining the syntax and functionality of the project.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Core.CustomProjections
{
    using System.Runtime.CompilerServices;

    using NHibernate.Criterion;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Core.CustomProjections" /> namespace contains several
    ///     <see cref="IProjection" /> implementations used in the project where the <see cref="IProjection" /> types
    ///     provided by <see cref="NHibernate" /> simply doesn't cut it.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Core.Implementations
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Core.Implementations" /> namespace contains implementations for the
    ///     fundamental parts of the project.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Core.Structures
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Core.Structures" /> namespace contains all classes used by
    ///     implementations in the <see cref="NHibernate.FlowQuery.Core.Implementations" /> namespace to hold data
    ///     about orders, joins, fetching strategies, etc.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Expressions
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Expressions" /> namespace contains all the basic filters used by the
    ///     <see cref="Is" /> helper.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Expressions.SubqueryExpressions
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Expressions.SubqueryExpressions" /> namespace contains all subquery
    ///     filters used by the <see cref="Is" /> helper.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.ExtensionHelpers
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.ExtensionHelpers" /> namespace contains static classes providing a wide
    ///     range of different extension methods that could be useful both within, and when using, the project.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Helpers
{
    using System.Runtime.CompilerServices;

    using NHibernate.Criterion;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Helpers" /> namespace contains static classes mainly providing utilities
    ///     to translate <see cref="System.Linq.Expressions" /> expressions and expression trees into something that
    ///     <see cref="NHibernate" /> understands (<see cref="IProjection" />,
    ///     <see cref="ICriterion" />, etc.).
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Revealing
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Revealing" /> namespace contains basic classes and interfaces used by
    ///     <see cref="NHibernate.FlowQuery" /> to reveal hidden members of objects.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Revealing.Conventions
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Revealing.Conventions" /> namespace contains a set of common revealing
    ///     conventions that can be used by <see cref="NHibernate.FlowQuery" /> to reveal hidden members of objects.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Helpers.ExpressionHandlers
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Helpers.ExpressionHandlers" /> namespace contains a set of definitions
    ///     describing the functionality for extending the handling of <see cref="System.Linq.Expressions.Expression" />
    ///     expressions in the expression trees used when projecting with <see cref="FlowQuery" />.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Helpers.ExpressionHandlers.Members
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Helpers.ExpressionHandlers.Members" /> namespace contains a set of 
    ///     definitions describing the functionality (and corresponding implementations) for extending the handling of 
    ///     <see cref="System.Linq.Expressions.MemberExpression" /> expressions in the expression trees used when 
    ///     projecting with <see cref="FlowQuery" />.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Helpers.ExpressionHandlers.MethodCalls
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Helpers.ExpressionHandlers.MethodCalls" /> namespace contains a set of 
    ///     definitions describing the functionality (and corresponding implementations) for extending the handling of 
    ///     <see cref="System.Linq.Expressions.MethodCallExpression" /> expressions in the expression trees used when 
    ///     projecting with <see cref="FlowQuery" />.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace NHibernate.FlowQuery.Helpers.ExpressionHandlers.Misc
{
    using System.Runtime.CompilerServices;

    /// <summary>
    ///     The <see cref="NHibernate.FlowQuery.Helpers.ExpressionHandlers.Misc" /> namespace contains a set of 
    ///     definitions describing the functionality (and corresponding implementations) for extending the handling of 
    ///     a various set of different <see cref="System.Linq.Expressions.Expression" /> expressions in the expression 
    ///     trees used when projecting with <see cref="FlowQuery" />.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}